name: nlp-summative
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas
  - scikit-learn
  - scipy=1.11.3
  - ipykernel
  - requests
  - tqdm
  - matplotlib
  - seaborn
  - nltk
  - wandb
  - nbformat
  - openpyxl
  - adjustText
  - spacy
  - pip
  - pip:
    - gensim==4.3.1
    - lingua-language-detector